### ISSUE TITLE
Add commas to generated numbers?

### ISSUE THREAD

**Issue by silentkrange** [mhuggins/jquery-countTo#31]
I'm banging my head against this one -- anyone know how to use this great countUp timer, but add commas in the appropriate places as it's counting up? (i.e. change 54321 to 54,321)

**Comment by mhuggins** [comment]
Hey @silentkrange, this question has been asked before.  [Here's some sample code](https://github.com/mhuggins/jquery-countTo/issues/19#issuecomment-31998103) that I provided there.  Hope that helps!  Feel free to reopen if you're still running into problems.
