### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by mkurz** [mhuggins/jquery-countTo#32]
Could you please tag your releases with `git tag`?
Thanks!

**Comment by mhuggins** [comment]
Done!  https://github.com/mhuggins/jquery-countTo/releases/tag/v1.0.0

**Comment by mhuggins** [comment]
Just out of curiosity, what package system are you using that needs this?

**Comment by mkurz** [comment]
Thanks!
I want to add your library to http://www.webjars.org/ - that's why :smirk:
