### ISSUE TITLE
Using data-count-to attribute instead of data-to messes up the script

### ISSUE THREAD

**Issue by marius-nyxpoint** [mhuggins/jquery-countTo#33]
Using the "data-count-to" attribute on the element seems to make the script count to the number specified + 1. In addition, the script seems to not stop updating the element(not tested but likely, because my laptop fan started whirling heavy).

I know that "data-to" should be used, I'm just pointing out a fun fact. I didn't read the docs and needed a way to dynamically pass the "to" config.

**Comment by mhuggins** [comment]
What does your code look like?  The `data-count-to` attribute you mentioned should be irrelevant to this plugin since it's not a supported attribute.

**Comment by mhuggins** [comment]
Gonna go ahead and close this since I haven't heard back.  Feel free to reopen if you're interested.
