### ISSUE TITLE
how to change number with persian number?

### ISSUE THREAD

**Issue by premier213** [mhuggins/jquery-countTo#34]
hi ,tnx u !
how to change number of counter to persian number ?

**Comment by mhuggins** [comment]
If you look at the [JavaScript Options section of the README](https://github.com/mhuggins/jquery-countTo#javascript-options), there's a `formatter` option that allows you to change the format of what's being rendered.  That should allow you to convert 0-9 to their Persian equivalents.

**Comment by premier213** [comment]
I am a beginner!
more to do

**Comment by premier213** [comment]
and i use for woocommerce this code show number of product 

<?php
$count_product =  get_scp_posts() ;
$persian_digits    =    array('۰','۱','۲','۳','۴','۵','۶','۷','۸','۹');
$english_digits    =    array('0','1','2','3','4','5','6','7','8','9');
$count_product = str_replace($english_digits, $persian_digits, $count_product); ?>

<?php echo $count_product ?>

when input in 
to: <?php echo $count_product ?>,

not work for me!!

**Comment by premier213** [comment]
please help

**Comment by mhuggins** [comment]
The problem is that the jQuery/JS is running on the client side, and PHP is running on the server side, so the two can't interact in the way you're trying to do so.  Instead, you'll need to use the `formatter` function I called out earlier, doing the character translating via JS.

A quick search shows how you might approach it [as explained here](http://stackoverflow.com/questions/286921/efficiently-replace-all-accented-characters-in-a-string).  For example:

```javascript
function translate(str, translate) {
  var lookup = new RegExp('(' + Object.keys(translate).join('|') + ')', 'g');

  return str.replace(lookup, function (match) { 
    return translate[match];
  });
}

$('.counter').countTo({
  from: 0,
  to: 100,
  formatter: function (value, options) {
    return translate(value, {'۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4', '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9'});
  }
});
```

**Comment by premier213** [comment]
tnx but notwork :(

**Comment by mhuggins** [comment]
Are you getting an error in the console?  If so, what error?  I haven't tried this, it was just a pseudocode example.

**Comment by mhuggins** [comment]
You might just need to cast the numeric value to a string to make it work, i.e. change `translate(value, ...)` to `translate(value.toString(), ...)`

**Comment by mhuggins** [comment]
Gonna go ahead and close this since I haven't heard back.  Let me know if this is still a problem for you.
