### ISSUE TITLE
how to counter run when seen in browser ?

### ISSUE THREAD

**Issue by premier213** [mhuggins/jquery-countTo#35]
hi ,tnx u !
how to counter run when seen in browser not when load page?

**Comment by mhuggins** [comment]
You'll need to test if the item is visible calling the `countTo` method.  Here's a StackOverflow question that relates to your question: http://stackoverflow.com/questions/487073/check-if-element-is-visible-after-scrolling

**Comment by premier213** [comment]
tnx u :)

**Comment by hlw-arif** [comment]
i am still confused

**Comment by NLdirect** [comment]
i dont understand which html code do i use to run my .js file?
