### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by YusufBesim** [mhuggins/jquery-countTo#37]
I want to use [Sourcegraph](https://sourcegraph.com) for jquery-countTo code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mhuggins/jquery-countTo. (It should only take 30 seconds.)

Thank you!

**Comment by mhuggins** [comment]
Sure, just did. :)
