### ISSUE TITLE
how to destroy the event

### ISSUE THREAD

**Issue by chamara-fg** [mhuggins/jquery-countTo#38]

**Comment by mhuggins** [comment]
That's not implemented, but would be a great addition!

**Comment by tobaiasjl** [comment]
#41

**Comment by mhuggins** [comment]
This can now be done with the `stop` function, e.g.: `$('#timer').countTo('stop')`

**Comment by zdimaz** [comment]
STOP LIKE A PAUSE!!
PLEASE TRIGGER DESTROY !
