### ISSUE TITLE
Can I count to a decimal number 

### ISSUE THREAD

**Issue by rdoddXL** [mhuggins/jquery-countTo#42]
I am doing a real estate application and I need the plugin to count up to 2.5 is this possible. I tried setting data-from="0" data-to="2.5"  but it just counts to 3 any suggestions.

**Comment by rept** [comment]
Looking for the same but a bit more difficult.  I have users who use comma as decimal separator.

**Comment by rept** [comment]
Wouldn't it be possible to have the possibility that we can hookup an function for the display?  So internally it works with integers (or even better floats) to calculate the timing and number of steps but for display it calls a function with the value param.  That way we could do display things like: $1,431.45 or €14.200,25

**Comment by rept** [comment]
Aha!  Found a nice solution.  You can just use the formatter function which works great:

    $this.countTo({
                    speed: 1500,
                    refreshInterval: 25,
                    formatter: function (value, options) {
                        return formatPriceCents(value);
                    }
    })

and in formatPriceCents you can do whatever you want.  Tested it, and it works fine.

BTW @rdoddXL thanks for this great library :-)

**Comment by mhuggins** [comment]
Yep, you should be able to format with the `formatter` callback.  Glad you like the plugin!  @rdoddXL let me know if this solves your issue.

**Comment by viniciusf84** [comment]
Is there a way to display it like: "1.200,88"?

**Comment by viniciusf84** [comment]
I've found the answer to my question here: <a href="https://github.com/mhuggins/jquery-countTo/issues/19">#19</a>

**Comment by mhuggins** [comment]
Glad you figured it out!
