### ISSUE TITLE
Bower package points to wrong repository

### ISSUE THREAD

**Issue by molejniczak** [mhuggins/jquery-countTo#43]
The bower repo points [here](http://github.com/Atolye15-packs/jquery-countTo.git") which gives a 404 error.

**Comment by mhuggins** [comment]
Where are you seeing that?  Here's the [bower.json link](https://github.com/mhuggins/jquery-countTo/blob/master/bower.json#L4).

**Comment by molejniczak** [comment]
When I try to install jquery-countTo through bower, I get the following:

```
$ bower install jquery-countTo
bower not-cached    git://github.com/Atolye15-packs/jquery-countTo.git#*
bower resolve       git://github.com/Atolye15-packs/jquery-countTo.git#*
bower not-cached    git://github.com/Atolye15-packs/jquery-countTo.git#*
bower resolve       git://github.com/Atolye15-packs/jquery-countTo.git#*
bower cached        git://github.com/imakewebthings/waypoints.git#3.1.1
bower validate      3.1.1 against git://github.com/imakewebthings/waypoints.git#
*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github
.com/Atolye15-packs/jquery-countTo.git", exit code of #128 fatal: remote error:
   Repository not found.

Additional error details:
fatal: remote error:
  Repository not found.
```

**Comment by molejniczak** [comment]
A quick workaround I've found is to just install it by pointing at your repo directly:

    bower install mhuggins/jquery-countTo

**Comment by mhuggins** [comment]
Yes, someone forked my repo and stole the name from me unfortunately.  You'll need to use "countTo" instead.

**Comment by mhuggins** [comment]
This is now fixed in bower.  You should be able to get it by the name `jquery-countTo`.  Thanks for letting me know so this could be fixed!
