### ISSUE TITLE
Support for commas in numbers?

### ISSUE THREAD

**Issue by nikibrown** [mhuggins/jquery-countTo#46]
I'm not a JS expert, but when I try to use data-to="25,000" as a data attribute I get a value of 'NAN' which makes sense. Curious how I could get commas in there?

**Comment by mhuggins** [comment]
https://github.com/mhuggins/jquery-countTo/issues/36
https://github.com/mhuggins/jquery-countTo/issues/31
https://github.com/mhuggins/jquery-countTo/issues/20
https://github.com/mhuggins/jquery-countTo/issues/19
https://github.com/mhuggins/jquery-countTo/issues/2

**Comment by nikibrown** [comment]
Whoops, sorry!
