### ISSUE TITLE
Multiple unique counts on a page

### ISSUE THREAD

**Issue by select-lewis-knight** [mhuggins/jquery-countTo#47]
Hi I'm having trouble using .countTo for multiple unique counts.
Below is a section of code that i'm using to loop through all the elements with the class .count and for the text() to be used as the 'to' options value. - one element's value is 70 and the other is 800.

						$('.count').each(function () {
							
						
							if(!$(this).hasClass('counter-complete')) {
							

								$(this).addClass('counter-complete').css('visibility', 'visible');

								var totalNumber = $(this).text();
								 
								jQuery(function($) {
									$('.count').countTo({
										from: 0,
										to: totalNumber,
										speed: 5500,
										decimals: 2,
										refreshInterval: 50,
									});
								});
								
							}
							
						});

The numbers just appear at their to value instantly and no error is put into the console.

Any help would be greatly appreciated. Cheers,

Lew.

**Comment by select-lewis-knight** [comment]
Edit ==============

I'm an idiot, the countTo is wrapped in a jQuery function by accident.

**Comment by mhuggins** [comment]
:+1: Glad you solved it!
