### ISSUE TITLE
How to make that counter started working when released into the scope of the screen?

### ISSUE THREAD

**Issue by kaskad88** [mhuggins/jquery-countTo#54]
Hi mhuggins,
I really like your plugin, nice and simple.
I have such a situation, my counter to find in the middle of the page and scroll down the page already no animation. How to make that counter started working when released into the scope of the screen?

**Comment by mhuggins** [comment]
I'm sorry, but I don't understand what you're asking.

**Comment by lamsharkie** [comment]
I think what kaskad88 is asking... and what I'm looking for as well, is a way to have the timer not start until it is in view of the viewport / browser window. 

I have the timer in a location that is down the page a little bit, and by the time my users would get there.... having the animation of the numbers counting up would be lost because the numbers would be static. 

If you could please update with a way ...or show an option of how to have the timer not start until the element that holds the timer comes into view. Thank you for the awesome plugin, and any help on accomplishing this feature would be greatly appreciated.

**Comment by lamsharkie** [comment]
Ok... A solution has been reached. I owe this to a great guy on StackOverflow who took the time to help me with this, Rayon Dabre.  @kaskad88 check out this [jsfiddle] (https://jsfiddle.net/lamsharkie/spe3ru39/) to see how to get the timer to only start when visible in the browser. There are hints in the HTML section that are helpful.

**Comment by mhuggins** [comment]
That looks about right to me.  There are plenty of plugins and JS functions that relate to checking scrolling and visibility, and that goal falls outside the scope of this plugin.

@lamsharkie It's worth mentioning that the jsfiddle solution you linked to will also need the `isScrolledIntoView` function defined, [as found here](http://stackoverflow.com/questions/487073/check-if-element-is-visible-after-scrolling):

```js
function isScrolledIntoView(elem) {
  var $elem = $(elem);
  var $window = $(window);

  var docViewTop = $window.scrollTop();
  var docViewBottom = docViewTop + $window.height();

  var elemTop = $elem.offset().top;
  var elemBottom = elemTop + $elem.height();

  return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
}
```

**Comment by mhuggins** [comment]
If that solution works for you guys, let me know, and I'll close this out.

**Comment by lamsharkie** [comment]
Oh crap! You're right. I shared the wrong [fiddle](https://jsfiddle.net/spe3ru39/1/). lol. 

Yes, that works perfectly. I assume that a large percentage of usage for counters like this need something like this. I am not sure if you would want to add this as an addition for those wanting this feature or not, but that's how I'm using it, and such an addition would have saved a lot of time. 

Again, thank you for the awesome plugin and thank you for being quick to respond.

**Comment by kaskad88** [comment]
Hi. Sorry for my English.
My version (jQuery):


(function ($) {
    var o = $('.count');
    var cc = 1;

    if (o.length > 0) {
        include('js/jquery.countTo.js');

        $(window).scroll(function(){
            var elemPos = o.offset().top;
            var elemPosBottom = o.offset().top + o.outerHeight();
            var winHeight = $(window).height();
            var scrollToElem = elemPos - winHeight;
            var winScrollTop = $(this).scrollTop();

            if (winScrollTop > scrollToElem) {
                if(elemPosBottom > winScrollTop){
                    if (cc < 2){
                        cc = cc + 2;
                        $(document).ready(function () {
                            $(o).countTo();
                        });
                    }
                }
            }
        });
    }
})(jQuery);

**Comment by mhuggins** [comment]
Thanks for sharing!
