### ISSUE TITLE
Decimal points?

### ISSUE THREAD

**Issue by mellis3** [mhuggins/jquery-countTo#55]
Is there currently a way to count with decimal points? Say i want to count to 5.4 it just counts to 5 right now and removes the decimal. 

Is there a way to keep the decimal easily?

Thanks!

**Comment by nickbijmoer** [comment]
I would like to know this too :D

**Comment by mhuggins** [comment]
You can supply a custom `formatter` to style as you like.  The default formatter converts to fixed integers.
