### ISSUE TITLE
Add a delay/sleep option before counting

### ISSUE THREAD

**Issue by SymbolCsaba** [mhuggins/jquery-countTo#62]
Allow delay/sleep in milliseconds before counting up/down. This allows the browser load all image/content and users can focus  to numbers.

if (settings.delay)
{
    setTimeout(function()
    {
        data.interval = setInterval(updateTimer, settings.refreshInterval);
    }, settings.delay);
}
else
    data.interval = setInterval(updateTimer, settings.refreshInterval);

**Comment by mhuggins** [comment]
I think the goal of what you're doing is similar to #54, in that it doesn't need to be backed into this package.  You could simply construct your JS to run it whenever you want, e.g.:

```js
setTimeout(function() {
  $('.timer').countTo();
}, 10000);
```
