### ISSUE TITLE
Add time

### ISSUE THREAD

**Issue by User0123456789** [mhuggins/jquery-countTo#63]
Add specific time when the counter will run. E.g. If the counter will only run from 7 am up to 12 pm every day.

**Comment by mhuggins** [comment]
I don't think this is a good candidate for this plugin, but it can easily be done with pure JS when integrating with it.

```js
var currentHour = new Date().getHours();

if (currentHour >= 7 && currentHour <= 12) {
  $('.timer').countTo();
}
```
