### ISSUE TITLE
Continual counter regardless of page refresh

### ISSUE THREAD

**Issue by User0123456789** [mhuggins/jquery-countTo#64]
Continue the counting of counter even the page is refresh or reopen

**Comment by mhuggins** [comment]
I'm unclear about what you're looking for with this issue.  Can you elaborate?

**Comment by User0123456789** [comment]
When I refresh or re-open the browser, the counting is back to the start

**Comment by mhuggins** [comment]
I'd suggest looking into local storage if you want to maintain a value.
