### ISSUE TITLE
Not able to Format with Decimals

### ISSUE THREAD

**Issue by luskbo** [mhuggins/jquery-countTo#66]
For some reason, I am unable to to get the formatting working with decimals. 
I have an example here: [https://jsfiddle.net/gxp8qrpp/](https://jsfiddle.net/gxp8qrpp/)
I used the countTo function to create counter and set the formatter through the options as described in your demo.

Any ideas?

**Comment by mhuggins** [comment]
Try adding `decimals: 2` (or however many decimals you want) as an option.

**Comment by mhuggins** [comment]
This shows that it's working.  Let me know if you run into any other problems!  https://jsfiddle.net/gxp8qrpp/1/

**Comment by luskbo** [comment]
Thanks man for the fast response! Feeling kinda stupid right now. I've been thinking decimal and just realized I meant commas... Is it possible to add commas to the format?

**Comment by mhuggins** [comment]
Sure check out #46.

**Comment by luskbo** [comment]
Man! If I owed you a beer for every time you have probably been asked that, I would probably be broke! 
Thanks again man!

**Comment by mhuggins** [comment]
No problem!
