### ISSUE TITLE
How to set a function repeat count?

### ISSUE THREAD

**Issue by krishnaprasadkc2** [mhuggins/jquery-countTo#73]
I want to run this counter only once when i reached to a particular div, how to do that?

`setInterval(financialCounter,0000);
            function financialCounter(){
              $('.counter__item__count').countTo({
                speed: 2000,
              });
            };`

**Comment by mhuggins** [comment]
You'll need to use standard JS API's for this.  Here's an example: https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/
