### ISSUE TITLE
refreshinterval is messed when "from" property is more than 0

### ISSUE THREAD

**Issue by pinoybai** [mhuggins/jquery-countTo#74]
Hi,

The count increment is not working properly when the 'from' property is set. please check the below fiddle:

https://jsfiddle.net/d6xwtvf8/

the count should increment in 50s (50, 100, 150, 200, 250 etc..,) but it in incrementing in random numbers.

could you please let me know what could be wrong?

**Comment by mhuggins** [comment]
This is working correctly.  It's incrementing by 49 on each render.  Your `from` is 50 and your `to` is 2500, with a `speed` of 2500 and a `refreshInterval` of 50.

```
(to - from) / (speed / refreshInterval)  ==>  (2500 - 50) / (2500 / 50)  ==>  2450 / 50  ==>  49
```

**Comment by pinoybai** [comment]
When I mention from:50 and refresh interval:50, it is incremented by 49.
May I know which number I should use for it to increment by 50? Like
50,100,150,200,250...etc...,
