### ISSUE TITLE
Multiple counter from .js?

### ISSUE THREAD

**Issue by nostartbutrings** [mhuggins/jquery-countTo#75]
Hi ,
is it possible to initialize multiple counter from a .js file?
Like 
```javascript
$('.countXY').countTo({ options here });
// and another one
$('.countABC').countTo({ options here });
```
but only the first is counting properly? Multiple counters with data-attribs is working fine...

Or let's say: how to use the formatter from data-attribs?

**Comment by mhuggins** [comment]
> is it possible to initialize multiple counter from a .js file?

Yes, it is possible.

> but only the first is counting properly?

I'd have to see a reproduction to know if it's an issue with the plugin vs. implementation.

> how to use the formatter from data-attribs?

This is up to you.  You can't specify a function as part of a data attribute, but you could specify data that relevant to a custom formatter, such as `data-precision`.

**Comment by nostartbutrings** [comment]
Thank you for your reply!
> I'd have to see a reproduction to know if it's an issue with the plugin vs. implementation.

Just tested again, it's working, my fault. Some settings were stupid, so it looked weird while counting. Sorry for that :-)
